### ISSUE TITLE
Sound distortion when using dellfan

### ISSUE THREAD

**Issue by snakehead007** [clopez/dellfan#3]
When I execute `sudo ./dellfan 1` or `sudo ./dellfan 2` while playing audio.
Is it possible to fix this?
also, thanks for making this great tool

**Comment by Wer-Wolf** [comment]
This is likely caused by SMM calls taking too long. Since the whole machine freezes while handling a SMM, a faulty SMM handler can cause audio glitches.

Make sure you are running the latest BIOS.
