### ISSUE TITLE
Config persistance

### ISSUE THREAD

**Issue by pinzaghi** [clopez/dellfan#5]
Are these changes supposed to be persistent on the BIOS? I need to disable the BIOS fan control at every startup.

Thanks for the great tool btw.

**Comment by clopez** [comment]
No, the changes are volatile. They will be lost on reboot. Sometimes (depending on the laptop) they are lost even after suspend and resume.

If you want something persistent I suggest to create a script or daemon that calls this program in the background as needed.

**Comment by pinzaghi** [comment]
Understood, gracias!
