### ISSUE TITLE
Works inconsistently with Dell Precision M6600

### ISSUE THREAD

**Issue by smcnally** [clopez/dellfan#6]
Thank you for this code. It has improved fan noise on my **Dell Precision M6600**.  This is FYI, but I appreciate any feedback you have for me.  

I've experienced what you've noted with power-offs vs suspending. I've also sometimes seen overall system sluggishness and high CPU and RAM utilization after using `dellfan` and continue to investigate that. Between `dellfan`, `i8kmon`, `thermald`, and `sensors`, I'm not sure if there's resource contention that's causing fans to spin at lower temperatures than the thresholds I've configured. I continue to investigate this.  

### `dellfan` + `i8kmon`
I'm using `i8kmon` and still get fans spinning at higher RPMs at lower temperatures than the thresholds I've configured. When this happens, I'll do the following which usually turns the fans off again: 

* stop i8kmon service 
* toggle dellfan on and then off  
* re-start i8kmon service 

I've also tried `dell-bios-fan-control` which is based on your code. 
https://github.com/TomFreudenberg/dell-bios-fan-control

### System Info 
Dell Precision M6600
Ubuntu 20.04 

`i8kctl` output: 
1.0 A18 J59D4S1 53 1 1 3413 3034 -1 -1

`sensors` output: 
```
dell_smm-virtual-0
Adapter: Virtual device
Processor Fan: 3034 RPM
Video Fan:     3410 RPM
CPU:            +53.0°C  
Ambient:        +52.0°C  
SODIMM:         +47.0°C  
SODIMM:         +47.0°C  
SODIMM:         +47.0°C  
GPU:            +62.0°C  

BAT0-acpi-0
Adapter: ACPI interface
in0:          12.68 V  
curr1:       1000.00 uA 

coretemp-isa-0000
Adapter: ISA adapter
Package id 0:  +55.0°C  (high = +86.0°C, crit = +100.0°C)
Core 0:        +54.0°C  (high = +86.0°C, crit = +100.0°C)
Core 1:        +48.0°C  (high = +86.0°C, crit = +100.0°C)
Core 2:        +55.0°C  (high = +86.0°C, crit = +100.0°C)
Core 3:        +50.0°C  (high = +86.0°C, crit = +100.0°C)

acpitz-acpi-0
Adapter: ACPI interface
temp1:        +25.0°C  (crit = +107.0°C)
```

![211001-HardwareSensors-Readout](https://user-images.githubusercontent.com/850878/135680865-5b673af1-6ad8-44c1-90d6-209ce0067be9.png)

**Comment by clopez** [comment]
The BIOS on some Dell models will try to auto-contol the fans by itself. So the BIOS will override any fan speed setting that you set. To avoid that you have to disable the BIOS control. This program let's you do that.

Execute it as follows to disable BIOS control
```
dellfan 1 1
```

And then try to use the other tools to see if now work better.

To bring back BIOS control execute:

```
dellfan 1 0
```

**Comment by clopez** [comment]
Note that in my case, after coming from suspension I have to re-execute the command to disable back the control of the BIOS since it gets re-activated somehow (no idea how and why) when suspending.

**Comment by smcnally** [comment]
Thank you, Carlos. I have been successfully using your `dellfan` code to disable BIOS fan control since before posting this Issue. I have stopped running `thermald` since posting this Issue, and fan speed and noise have improved with BIOS disabled and `i8kmon` controlling the fans. 

With BIOS control disabled, however, I am seeing lag in UI response e.g. to typing, mouse clicks, and window focus changes. I don't know how to measure or quantify this lag, but it's more lag than with BIOS control enabled. Bringing back BIOS control with `dellfan 1 0` makes the UI lag go away, but the fan noise returns. 

I have process lists and **System Monitor** screenshots taken when this UI lag is occurring, but I'm not clear about what's causing the lag. Do you have thoughts on what might cause UI lag when BIOS fan control is disabled? Many thanks, again, for your assistance.

**Comment by clopez** [comment]
> With BIOS control disabled, however, I am seeing lag in UI response e.g. to typing, mouse clicks, and window focus changes. I don't know how to measure or quantify this lag, but it's more lag than with BIOS control enabled. Bringing back BIOS control with `dellfan 1 0` makes the UI lag go away, but the fan noise returns.

It seems likely that your computer is overheating with the fans at low level so the CPU frequency gets throttled down to avoid a major problem. When that happens the computer runs slow.

Check in the kernel log (command ```sudo dmesg```) if there is any report about this. You should see some lines like:
```
CPU1: Package temperature above threshold, cpu clock throttled (total events = 2582)
```

If that is the case, the best you can do is to re-apply the thermal compound on the CPU and GPU of your Laptop. This thermal compounds don't last in good state more than a few years. You usually have to re-apply them each ~2 years to keep the laptop properly refrigerated. If you still have warranty you can call the technical service and tell them that your computer is overheating and that you want the thermal compound re-applied. If is not under warranty you can try to do that yourself if you feel like disassembling the laptop and applying it. I can recommend the `ARCTIC MX-4` thermal compound. Is non-conductive and really good at lowering the temperatures, is even better than the one that the stock one that Dell applies.

**Comment by smcnally** [comment]
Many thanks again, Carlos. 

Nothing in kernel log for 'temperature', 'threshold' or 'throttled'. I do see CPUs Up and offline: 

> smpboot: CPU 7 is now offline
> IRQ 43: no longer affine to CPU6

and Enabling and Disabling non-boot CPUs.

> Enabling non-boot CPUs ...
> Disabling non-boot CPUs ...

Your `ARCTIC MX-4` recommendation is good. This machine is well-overdue and will benefit.

kernel log is a good source -- I'll look more there. System resources don't look over-taxed by eye. Even watching a ~:40 second Blender render, there are available CPU and RAM resources. I'll create a follow-up Issue with my discoveries. 

![image](https://user-images.githubusercontent.com/850878/136125383-4e0b6e80-dddf-4c73-96e1-9748cceaa04b.png)

![image](https://user-images.githubusercontent.com/850878/136125604-d4874ae6-49a0-48dd-b974-42b0eeaf6d9b.png)

**Comment by smcnally** [comment]
We can close this Issue. I'll create a follow-up Issue with more specifics from my discovery.

**Comment by clopez** [comment]
You're welcome.

A tip: You can try to run this command ```openssl speed -multi $(nproc)``` on the terminal, it will benchmark the openssl speed with all your cores so your CPU will be put to 100% usage. Let it run for some minutes and then monitor the temperature of the CPU (it should not go above 95ºC) as well as the kernel log to see if there is some log of CPU throttling events due to high temperatures.
