### ISSUE TITLE
UI sluggishness with BIOS control disabled -- errors from logs - FYI-only 

### ISSUE THREAD

**Issue by smcnally** [clopez/dellfan#7]
This is FYI-only as follow-up to my previous issue using `dellfan` with the Dell M6600.  #6 

### log errors 

Monitoring all logs while running the openssl speed benchmark, there's no clear culprit to UI lags. These are errors I've found and will investigate. 

* ima: Error Communicating to TPM chip
* perf: interrupt took too long (2929 > 2500), lowering kernel.perf_event_max_sample_rate to 68250
* acpi PNP0A08:00: _OSC failed (AE_ERROR); disabling ASPM
* (reported by gnome-shell): 
```
JS ERROR: TypeError: this._workspacesViews[i] is undefined
_updateWorkspacesFullGeometry@resource:///org/gnome/shell/ui/workspacesView.js:756:13
setWorkspacesFullGeometry@resource:///org/gnome/shell/ui/workspacesView.js:746:14
setWorkspacesFullGeometry@resource:///org/gnome/shell/ui/viewSelector.js:301:33
_updateWorkspacesGeometry@resource:///org/gnome/shell/ui/overviewControls.js:498:27
vfunc_allocate@resource:///org/gnome/shell/ui/overviewControls.js:402:14
_computeWindowCenter@resource:///org/gnome/shell/ui/workspace.js:302:35
_init@resource:///org/gnome/shell/ui/workspace.js:160:14
_addWindowClone@resource:///org/gnome/shell/ui/workspace.js:1856:21
_init@resource:///org/gnome/shell/ui/workspace.js:1174:22
_updateWorkspaces@resource:///org/gnome/shell/ui/workspacesView.js:232:29
_init@resource:///org/gnome/shell/ui/workspacesView.js:91:14
_updateWorkspacesViews@resource:///org/gnome/shell/ui/workspacesView.js:682:24
show@resource:///org/gnome/shell/ui/workspacesView.js:612:14
show@resource:///org/gnome/shell/ui/viewSelector.js:276:33
_animateVisible@resource:///org/gnome/shell/ui/overview.js:580:27
show@resource:///org/gnome/shell/ui/overview.js:566:14
toggle@resource:///org/gnome/shell/ui/overview.js:689:18
_initializeUI/<@resource:///org/gnome/shell/ui/main.js:223:22
```
### Suspend to RAM consistently non-functional 

As you note in [README](https://github.com/clopez/dellfan/blob/master/README.md),  

| Suspend to RAM sometimes stops working: The laptop will power itself off instead of suspending.

I'm seeing this issue 100% of the time. Suspend does not work with BIOS disabled. Machine consistently shuts down vs Suspending. I've disabled auto-suspend. I've re-enabled BIOS control before manually suspending the machine - BUT ... 
Suspend still shuts down instead even when explicitly re-enabling BIOS control and manually triggering Suspend 
This will be a hard-stop for me tweaking fan settings if Suspend to RAM is non-functional 

### **Dell Precision M6600** usage notes - `dellfan` and `i8kmon` 
For all notes below: 
- `thermald` service is stopped and disabled 
- `i8kmon` service is on
- BIOS control is disabled via `dellfan`

Fans sometimes still spin up even below trigger temperatures
- Only after an hour+ of continuous usage  

Order of Operations makes a difference with fan high RPMs below trigger temperatures 
- Starting, Stopping, restarting `i8kmon`
- disabling, enabling BIOS control w `dellfan`
- `i8kfan 1 0` explicitly works well (when BIOS control is disabled)

When I'm experiencing UI sluggishness, toggling BIOS control back on and off again addresses responsiveness issues   

The Dell M6600 handles and recovers from stress well -- fans spin up and back down  
- "Normal load" includes a dozen Firefox windows, VSCode, several open terminals
- Stress loads include these plus  
    - Blender renders 
    - additional web pages that are javascript- and multimedia-heavy
    - the openssl smp test (details following)

`openssl speed -multi $(nproc)`
- did a fine job saturating available system resources
- machine recovered well a few moments after stopping this process 
- still nothing in kernel log for 'temperature', 'threshold' or 'throttled' 
- All (perhaps) related errors I've found are in the first section of this Issue

**Comment by Wer-Wolf** [comment]
Maybe the SMM calls of i8kutils, etc are taking too long? Since SMM calls block the entire PC, a slow SMM handler may cause such effects.

Are you running the latest BIOS?
